networks:
  xwiki-network:
    external: true

volumes:
  xwiki-data:
  xwiki-postgres:
  xwiki-backups:
  xwiki-logs:

services:
  postgres:
    image: ${XWIKI_POSTGRES_IMAGE_TAG}
    volumes:
      - xwiki-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${XWIKI_DB_NAME}
      POSTGRES_USER: ${XWIKI_DB_USER}
      POSTGRES_PASSWORD: ${XWIKI_DB_PASSWORD}
    networks:
      - xwiki-network
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${XWIKI_DB_NAME}", "-U", "${XWIKI_DB_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    restart: unless-stopped

  xwiki:
    image: ${XWIKI_IMAGE_TAG}
    volumes:
      - xwiki-data:${DATA_PATH}
      - xwiki-logs:/usr/local/tomcat/logs
    environment:
      DB_HOST: postgres
      DB_DATABASE: ${XWIKI_DB_NAME}
      DB_USER: ${XWIKI_DB_USER}
      DB_PASSWORD: ${XWIKI_DB_PASSWORD}
    ports:
    - "8080:8080"
    networks:
      - xwiki-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy

  backups:
    user: "0:0"
    image: ${XWIKI_BACKUP_IMAGE_TAG}
    build:
      context: ./docker/backups
      args:
        POSTGRES_BASE_IMAGE: ${XWIKI_POSTGRES_IMAGE_TAG}
    command: sh /scripts/xwiki-backup-runner.sh
    volumes:
      - xwiki-data:${DATA_PATH}
      - xwiki-backups:${XWIKI_BACKUPS_PATH}
      - ./scripts:/scripts:ro
    environment:
      XWIKI_DB_NAME: ${XWIKI_DB_NAME}
      XWIKI_DB_USER: ${XWIKI_DB_USER}
      PGPASSWORD: ${XWIKI_DB_PASSWORD}
      BACKUP_INIT_SLEEP: ${BACKUP_INIT_SLEEP}
      BACKUP_INTERVAL: ${BACKUP_INTERVAL}
      BACKUP_PRUNE_DAYS: ${BACKUP_PRUNE_DAYS}
      XWIKI_BACKUPS_PATH: ${XWIKI_BACKUPS_PATH}
      XWIKI_BACKUP_NAME: ${XWIKI_BACKUP_NAME}
      DATA_PATH: ${DATA_PATH}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME:-}
      S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID:-}
      S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY:-}
      S3_REGION: ${S3_REGION:-}
      S3_ENDPOINT_URL: ${S3_ENDPOINT_URL:-}
      S3_PREFIX: ${S3_PREFIX:-}
    networks:
      - xwiki-network
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
